kind = "web"
previewPath = "/"
title = "Rabee Academia"
version = "1.0.0"
id = "artifacts/rabee-academia"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20924

[services.development]
run = "pnpm --filter @workspace/rabee-academia run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/rabee-academia", "run", "build" ]
publicDir = "artifacts/rabee-academia/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20924"
BASE_PATH = "/"
